### ISSUE TITLE
cannot import name 'discover_devices'

### ISSUE THREAD

**Issue by Joshuaalbert** [hbldh/pymetawear#43]
After building with `python setup.py build` and trying
```
from pymetawear.client import discover_devices
```
I get,
```
ImportError: cannot import name 'discover_devices'
```

## System 
python 3.6 from conda Fedora 25

**Comment by hbldh** [comment]
After building with `python setup.py build` you only get a built package and depending on from where you call your script, it is not certain that the package is in your path. I prefer using `pip install -e .` to install it in development mode instead.

However, this error is due to an error in the README I guess, where is says that the `discover_devices` should be imported from the `client` module. It have moved it, but missed updating that in README.

Use
```
from pymetawear.discover import discover_devices
```
instead. Will modify this in the development branch until next release which is under way.
