### ISSUE TITLE
Data returned from sensor not valid json

### ISSUE THREAD

**Issue by totuni** [hbldh/pymetawear#62]
* pymetawear version:   latest
* Python version:  3.8 
* Operating System:  windows 10

### Description

{'epoch': 1583781566117, 'value': {x : 0.108, y : 0.768, z : 0.689}}

I am trying to parse this but it is not valid json.  So I can not solve for x. 
data['value']['x']   this fails.   
I don't understand why data is semi json?  Is there an extraction of x example? 

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by hbldh** [comment]
Notice the missing `'` around `x`, `y` and `z`? It cannot be parsed as json since it is not json. It is actually a `[CartesianFloat`](https://github.com/mbientlab/MetaWear-SDK-Cpp/blob/master/bindings/python/mbientlab/metawear/cbindings.py#L710-L727) returned from the `metawear` package, which handles all communication with the board.

It can be accessed as `data['value'].x` if I recall correctly.
